config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pictures#index'
  resources :pictures do
    member do
      put :reject
      put :approve
    end
  end
  get '/pending', to: 'pictures#pending'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/picture.rb
# frozen_string_literal: true

class Picture < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  has_attached_file :image, styles: { large: '600x600>', medium: '400x300>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
  scope :approved, -> { where(status: 'approved') }
  scope :pending_approval, -> { where(status: 'pending') }
  scope :rejected, -> { where(status: 'rejected') }
  scope :without_rejected, -> { where.not(status: 'rejected') }

  def approved?
    status == 'approved'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:google_oauth2]

  has_many :pictures, dependent: :destroy

  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    user ||= User.create(
      email: data['email'],
      password: Devise.friendly_token[0, 20]
    )
    user
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  around_action :switch_locale

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end
end

app/controllers/pictures_controller.rb
# frozen_string_literal: true

class PicturesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @pictures = Picture.approved
  end

  def create
    @picture = Picture.create(pictures_params)
    if @picture.persisted?
      redirect_to pictures_path
    else
      render json: @picture.errors, status: :unprocessable_entity
    end
  end

  def edit
    find_params_id
  end

  def approve
    find_params_id
    @picture.update!(status: 'approved')
    redirect_to pictures_path
  end

  def reject
    find_params_id
    @picture.update!(status: 'rejected')
    redirect_to pictures_path
  end

  def pending
    if current_user.try(:admin?)
      @pictures = Picture.pending_approval
      render 'partials/admin_index'
    else 
      redirect_to pictures_path
    end
  end

  private

  def pictures_params
    params.permit(:image, :description).merge(user: current_user)
  end

  def find_params_id
    @picture = Picture.find(params[:id])
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

module Users
  class OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def google_oauth2
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra')
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/pictures_helper.rb
# frozen_string_literal: true

module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGallery2021</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user&.admin %>
      <%= render "partials/admin_header" %>
    <% else %>
      <%= render "partials/header" %>
    <% end %>
    <%= yield %>
  </body>
</html>
 

app/views/partials/_admin_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-static-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">TheGallery</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </form>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link admin-photos" href="/pending">Photos under consideration</a>
          </li>
          
          </li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle admin-name" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  ADMIN
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" data-method="delete" href="/users/sign_out">Sign out</a>
                </div>
              </div>
            </li>
          <% else %>
              <a class="nav-link" href="/users/sign_in">Sign in</a>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/partials/_header.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-light navbar-static-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">TheGallery</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <form class="form-inline my-2 my-lg-0">
          <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        </form>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/pictures/new">Submit a photo</a>
          </li>
          
          <li class="nav-item dropdown">
            <div class="dropdown">
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Language
              </a>
              <div class="dropdown-menu dropdown-menu-center" aria-labelledby="navbarDropdown">
              <%= link_to_unless I18n.locale == :en, "English", locale: :en %></p>
              <%= link_to_unless I18n.locale == :ru, "Русский", locale: :ru %>
              </div>
            </div>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item dropdown">
              <div class="dropdown">
                <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%= current_user.email %>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" data-method="delete" href="/users/sign_out">Sign out</a>
                </div>
              </div>
            </li>
          <% else %>
              <a class="nav-link" href="/users/sign_in">Sign in</a>
          <% end %>
        </ul>
      </div>
    </div>
</nav>

app/views/partials/admin_index.html.erb
<% if @pictures %>
  <div class="container">
    <% displayed_pictures = @pictures + Array.new(@pictures.size%3) %>
    <% displayed_pictures.each_slice(3) do |slice| %>
    <div class="row">
      <% slice.each do |picture| %>
        <div class="col">
          <div class="photo photo_img">
            <%= link_to image_tag(picture.image.url(:medium)), edit_picture_path(picture) if picture.present? %>
          </div>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
<% else %>
  <div>
    <a style="text-align: center;">There is no photos under consideration</a>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<div class="admin-form">
  <div class="admin-form-image">
    <img src="<%= @picture.image.url(:medium) %>">
  </div>

  <div class="admin-form-description">
	  <% if @picture.description != "" || @picture.description  %>
      <h3>Description:</h3>
		  <textarea cols="55" rows="4" readonly>
    		<%= @picture.description %>
			</textarea>
		<% end %>
  </div>
  <% if current_user.admin? && @picture.status == 'pending' %>
  <div class="admin-form-links">
    <hr class="admin-form-hr">
    <%= link_to 'Approve', approve_picture_path(@picture), method: :put %>
    <a>OR</a>
    <%= link_to 'Reject', reject_picture_path(@picture), method: :put %>
  </div>
  <% end %>
</div>

app/views/pictures/index.html.erb
<div class="header_image img-fluid" style="background-image: url(<%= asset_path '159.jpg' %>)">
  <div class="header_text_image">
  <h1>Welcome to The Gallery<h1>
  </div>
</div>

<div class="container">
  <% displayed_pictures = @pictures + Array.new(@pictures.size%3) %>
  <% displayed_pictures.each_slice(3) do |slice| %>
  <div class="row">
  <% slice.each do |picture| %>
    <div class="col">
      <div class="photo photo_img">
        <%= link_to image_tag(picture.image.url(:medium)), edit_picture_path(picture) if picture.present? %>
      </div>
  </div>
<% end %>
<% end %>
</div>

<br />

</div>

app/views/pictures/new.html.erb
<div class="row d-flex justify-content-center mt-100">
  <div class="col-md-8">
    <div class="card">
      <div class="card-header">
        <h5 style="color:grey;"><%= t :add_new_picture %></h5>
      </div>
      <div class="card-block">
        <%= form_tag pictures_path, method: :post, multipart: true do %>
          <span class="btn btn-secondary btn-file">
            Choose File
            <%= file_field_tag :image %>
          </span></p>
        <textarea name="description" id="description" class="form-control" placeholder="Add your description" minlength="0" maxlength="219" rows="2">
        </textarea>
        <div class="text-center m-t-20">
          <%= button_tag(type: 'submit', class: "btn btn-primary") do %>
            Upload now
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>
</div>